### ISSUE TITLE
64 bit pointers?

### ISSUE THREAD

**Issue by jkwashbourne-oss** [milankl/ZfpCompression.jl#22]
We ran into a case where 64-bit pointers are required, and ZfpCompression is failing with a truncation error. I am wondering why the choice to use 32 bit pointers? Why not use `Clong` instead of `Cint`? Is it possible to switch to 64-bit integers?

**Comment by milankl** [comment]
I believe this is a question for zfp's c implementation, not the Julia bindings here which has to map directly to the types used in zfp?

**Comment by jkwashbourne-oss** [comment]
The ZFP c bindings use `ptrdiff_t` which supports 64 bit. This packages uses `Cint` instead of `Clong` which I think is the problem.

**Comment by jkwashbourne-oss** [comment]
see for example

https://github.com/milankl/ZfpCompression.jl/blob/f09d78418c4d2e800539efbae0e0f07e9a0446c8/src/zfp.jl#L85

**Comment by milankl** [comment]
Feel free to open a pull request swapping those for `Clong` and see whether tests pass?

**Comment by jkwashbourne-oss** [comment]
Tests pass locally with `Clong`
Ill try to get the fork/pr soon
