### ISSUE TITLE
Request to add OMP threading

### ISSUE THREAD

**Issue by ktnihei** [milankl/ZfpCompression.jl#8]
Milan,

Many thanks for putting together this zfp compression package!

Would it be possible to enable OMP threading? Reading the zfp-0.5.5 docs, it appears that it can be enabled on compression (but not on decompression).

Thanks!
Kurt

**Comment by milankl** [comment]
Hey Kurt,
I haven't looked into any parallel compression with zfp. Without much effort everything can be added that still just calls a function from the library, as we can write this in Julia as `ccall(...` I don't know how to set-up the OMP threading in zfp, and almost on leave for the rest of August. You could check what needs to be done on the C-side to enable OMP, post it here and I'm happy to have a look at it in September?

**Comment by ktnihei** [comment]
Milan,

I think there are only 4 additional zfp calls needed, plus enabling the OMP compiler flag. Maybe we can talk in September. I’ll send you the needed changes in the meantime. 

Regards,
Kurt

**Comment by milankl** [comment]
Sounds good! Happy to accept any pull requests or code suggestions.

**Comment by milankl** [comment]
@ktnihei OpenMP is now available in v0.2 see the README. However, it's not available in macOS as the underlying C library from zfp_jll is not automatically built with OpenMP enabled...

**Comment by milankl** [comment]
@ktnihei On linux it works just out of the box though!

**Comment by ktnihei** [comment]
Milan,

Many thanks for adding the OMP threading! My apologies for not helping out with this enhancement.

Kurt
